### ISSUE TITLE
想了解一下，这个官方网页数据接口怎么来的

### ISSUE THREAD

**Issue by WParline** [doupoa/GetEPICFreeGames#2]
我试了一下，目前获取的信息不是百分百免费的，于是我打算改一下，改成能找到免费的

还有，希望能跟 这位gayhub同学交流交流！

**Comment by doupoa** [comment]
感谢您的回复！程序所用接口是从epic商店网页版中扣出来的，您只需在浏览器中按F12-网络 中刷新网页就可以收集到传输到您浏览器上的所有数据，随后筛选有相关数据的接口即可。由于官方接口时不时会改动，这样会导致程序无法正常获取数据。因此建议您使用相关RSS订阅




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "doupoa/GetEPICFreeGames"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月8日(星期五) 下午2:12
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[doupoa/GetEPICFreeGames] 想了解一下，这个官方网页数据接口怎么来的 (Issue #2)





 
我试了一下，目前获取的信息不是百分百免费的，于是我打算改一下，改成能找到免费的
 
还有，希望能跟 这位gayhub同学交流交流！
